"""
    Perioder{P<:AbstractVector{<:Integer}, T<:AbstractArray{P}, S<:AbstractArray{P}, C<:AbstractVector{<:Tuple}}

The information needed in performing periodic procedure. 
"""
struct Perioder{P<:AbstractVector{<:Integer}, T<:AbstractArray{P}, S<:AbstractArray{P}, C<:AbstractVector{<:Tuple}}
    map₁::T
    map₂::S
    channels::C
end 

"""
    Perioder(unitcell::QLattice, cluster::QLattice, table::Table)

Obtain the periodic information from the lattice system.

WARNING : User should ensure that the cluster you choosed is compatible with the lattice generated by the unitcell you input and the unitcell you input should be enclosed in the cluster you choosed sharing an original point with the cluster.

The periodized Green-function basis is ordered as
`(spin, orbital) channel × unit-cell site`.  More explicitly, `Perioder` first
sorts the `table` keys by their table sequence, collects sorted spin and orbital
labels, and builds

```julia
map₁[spin_index, orbital_index]
```

as the cluster-table indices with that spin/orbital channel across all cluster
sites.  It also builds

```julia
map₂[unitcell_site]
```

as the cluster sites equivalent to each site in `unitcell` under translations
by `unitcell.vectors`.  `perGreenFunction` then reshapes the periodized matrix
so the final row/column index runs fastest over unit-cell sites inside each
spin/orbital channel:

```text
(spin₁, orbital₁, unitcell_site₁),
(spin₁, orbital₁, unitcell_site₂),
...,
(spin₁, orbital₂, unitcell_site₁),
...
(spin₂, orbital₁, unitcell_site₁),
...
```

For a Gorkov Green function, the returned matrix is assembled as
`[G11 G12; G21 G22]`, and each block uses this same periodized basis order.
"""
function Perioder(unitcell::QLattice, cluster::QLattice, table::Table)
    @assert !isempty(unitcell.vectors) "the vectors in unitcell cannot be empty !"
    seq = sort(collect(keys(table)), by = x -> table[x])
    nspin, norbi, channels = sort(collect(Set(key[1] for key in seq))), sort(collect(Set(key[3] for key in seq))), Vector{Tuple{Vector{Int64},Vector{Int64}}}()
    map₁ = [filter(k -> nspin[i]==seq[k][1]&&norbi[j]==seq[k][3], 1:length(seq)) for i in eachindex(nspin), j in eachindex(norbi)]
    map₂ = [filter(j -> issubordinate(cluster.coordinates[:,j]-unitcell.coordinates[:,i], unitcell.vectors), 1:length(cluster)) for i in 1:length(unitcell)]
    for i in 1:size(map₁, 1), j in 1:size(map₁, 2), u in 1:size(map₁, 1), v in 1:size(map₁, 2) 
        push!(channels, ([i, j], [u, v]))
    end
    return Perioder(map₁, map₂, channels)
end


"""
    CPT{L<:QLattice, G<:EDSolver, P<:Perioder} 

CPT method for a quantum lattice system.
"""
struct CPT{L<:QLattice, C<:QLattice, G<:AbstractArray, P<:Perioder}
    unitcell::L
    cluster::C
    origigenerator::OperatorGenerator
    refergenerator::OperatorGenerator
    table::Table
    gfrw::G
    perioder::P
end


function CPT(
            unitcell::QLattice, 
            cluster::QLattice, 
            hilbert::Hilbert, 
            origiterms::Tuple{Vararg{Term}}, 
            referterms::Tuple{Vararg{Term}}, 
            gfrw::AbstractArray{ComplexF64, 3}; 
            neighbors::Union{Nothing, Int, Neighbors}=nothing)
    table = Table(hilbert, OperatorIndexToTuple(:spin, :site, :orbital))
    isnothing(neighbors) && (neighbors = maximum(term->term.bondkind, origiterms))
    origibonds = bonds(cluster, neighbors)
    referbonds = filter(bond -> isintracell(bond), origibonds)
    perioder = Perioder(unitcell, cluster, table) 
    origigenerator, refergenerator = OperatorGenerator(origibonds, hilbert, origiterms), OperatorGenerator(referbonds, hilbert, referterms)
    return CPT(unitcell, cluster, origigenerator, refergenerator, table, gfrw, perioder)
end

"""
    origiQuadraticTerms!(normal::Bool, om::AbstractMatrix, oops::AbstractVector, oopsseqs::AbstractVector,k::AbstractVector)

Calculate the Hamiltonian's quadratic terms of the original system.
"""
function origiQuadraticTerms!(normal::Bool, om::AbstractMatrix, oops::AbstractVector, oopsseqs::AbstractVector,k::AbstractVector)
    !normal&&(pm = copy(om))
    for i in eachindex(oops)
        seq₁, seq₂, n₁, n₂ = oopsseqs[i][1], oopsseqs[i][2], oopsseqs[i][3], oopsseqs[i][4]
        phase = exp(im*dot(k, icoordinate(oops[i])))
        om[seq₁, seq₂] += oops[i].value*phase
        !normal&&(n₁==2&&n₂==1)&&(pm[seq₁, seq₂] += oops[i].value*(phase'))
    end
    if !normal
        om[Vector(1:(size(om,1)÷2)), Vector(1:(size(om,1)÷2))] /= 2
        om[Vector((size(om,1)÷2+1):size(om,1)), Vector((size(om,1)÷2+1):size(om,1))] = -transpose(pm[Vector(1:(size(om,1)÷2)), Vector(1:(size(om,1)÷2))])/2
        om = 2om
    end
    return om
end

"""
    referQuadraticTerms(normal::Bool, rops::AbstractVector, rm::AbstractMatrix, table::Table)
    
Calculate the Hamiltonian's quadratic terms of the reference system.
"""
function referQuadraticTerms(normal::Bool, rops::AbstractVector, rm::AbstractMatrix, table::Table)
    for rop in rops 
        rop[1].index.internal.nambu==2 ? seq₁=table[rop[1].index'] : seq₁=(table[rop[1].index]+length(table))
        rop[2].index.internal.nambu==1 ? seq₂=table[rop[2].index] : seq₂=(table[rop[2].index']+length(table))
        rm[seq₁, seq₂] += rop.value
    end
    if !normal
        rm[Vector(1:length(table)),Vector(1:length(table))] /= 2
        rm[Vector(length(table)+1:2*length(table)),Vector(length(table)+1:2*length(table))] = -transpose(rm[Vector(1:length(table)),Vector(1:length(table))])
        rm = 2rm
    end
    return rm
end

"""
    seqs(oops::AbstractVector, table::Table)

The index's sequences of original system operators.
"""
function seqs(oops::AbstractVector, table::Table)
    seqs = [zeros(Int, 2) for _ in 1:length(oops)]
    for i in eachindex(oops)
        oops[i][1].index.internal.nambu==2 ? seq₁=table[oops[i][1].index'] : seq₁=(table[oops[i][1].index]+length(table))
        oops[i][2].index.internal.nambu==1 ? seq₂=table[oops[i][2].index] : seq₂=(table[oops[i][2].index']+length(table))
        seqs[i] = [seq₁, seq₂, oops[i][1].index.internal.nambu, oops[i][2].index.internal.nambu]
    end
    return seqs
end

"""
    CPTcore(cgfm::AbstractMatrix, vm::AbstractMatrix)

The calculating core of the CPT method.
"""
function CPTcore(cgfm::AbstractMatrix, vm::AbstractMatrix)
    result = Matrix{ComplexF64}(I, size(vm)...)
    return cgfm*inv(mul!(result, vm, cgfm, -1, 1))
end

function _cpt_normal_and_size(cpt::CPT, normal::Union{Nothing, Bool})
    size(cpt.gfrw, 1) == size(cpt.gfrw, 2) || throw(DimensionMismatch("Cluster Green function matrices must be square."))
    table_size = length(cpt.table)
    gf_size = size(cpt.gfrw, 1)
    inferred = if gf_size == table_size
        true
    elseif gf_size == 2table_size
        false
    else
        throw(DimensionMismatch("Cluster Green function matrix size $(gf_size) is incompatible with table size $(table_size). Expected $(table_size) for normal Green function or $(2table_size) for Gorkov Green function."))
    end
    if !isnothing(normal) && normal != inferred
        throw(ArgumentError("normal=$normal is inconsistent with the cluster Green function matrix size $(gf_size)."))
    end
    return inferred, gf_size
end

function _positive_axis_weights(xs::AbstractVector)
    length(xs) > 1 || throw(ArgumentError("At least two imaginary-frequency points are required when weights are not provided."))
    weights = zeros(Float64, length(xs))
    for i in 2:length(xs)
        step = xs[i] - xs[i-1]
        step > 0 || throw(ArgumentError("Imaginary-frequency points must be strictly increasing."))
        weights[i-1] += step/2
        weights[i] += step/2
    end
    return weights
end

function _gp_weights(iws::AbstractVector, weights::Nothing, nfreq::Int)
    length(iws) == nfreq || throw(DimensionMismatch("The number of imaginary-frequency points must match size(cpt.gfrw, 3)."))
    return _positive_axis_weights(iws)
end
function _gp_weights(iws::AbstractVector, weights::AbstractVector, nfreq::Int)
    length(iws) == nfreq || throw(DimensionMismatch("The number of imaginary-frequency points must match size(cpt.gfrw, 3)."))
    length(weights) == nfreq || throw(DimensionMismatch("The number of quadrature weights must match size(cpt.gfrw, 3)."))
    return Float64.(weights)
end
function _gp_weights(weights::AbstractVector, nfreq::Int)
    length(weights) == nfreq || throw(DimensionMismatch("The number of quadrature weights must match size(cpt.gfrw, 3)."))
    return Float64.(weights)
end

function _cpt_vm_matrices(normal::Bool, cpt::CPT, bz::Union{AbstractVector, ReciprocalSpace}, matrix_size::Int)
    oops = filter(op -> length(op) == 2, collect(expand(cpt.origigenerator)))
    rops = filter(op -> length(op) == 2, collect(expand(cpt.refergenerator)))
    oopsseqs = seqs(oops, cpt.table)
    rm = referQuadraticTerms(normal, rops, zeros(ComplexF64, matrix_size, matrix_size), cpt.table)
    vmvec = Vector{Matrix{ComplexF64}}(undef, length(bz))
    for i in eachindex(bz)
        vmvec[i] = origiQuadraticTerms!(normal, zeros(ComplexF64, matrix_size, matrix_size), oops, oopsseqs, bz[i]) - rm
    end
    return vmvec
end

function _cpt_order_matrix(normal::Bool, cpt::CPT, opterms::Tuple, matrix_size::Int)
    if isempty(opterms)
        return Matrix{ComplexF64}(I, matrix_size, matrix_size)
    end
    opbonds = filter(bond -> isintracell(bond), bonds(cpt.cluster, maximum(term -> term.bondkind, opterms)))
    opgenerator = OperatorGenerator(opbonds, cpt.refergenerator.hilbert, opterms)
    ops = filter(op -> length(op) == 2, collect(expand(opgenerator)))
    return referQuadraticTerms(normal, ops, zeros(ComplexF64, matrix_size, matrix_size), cpt.table)
end

function _cpt_trvm(normal::Bool, vmvec::AbstractVector, matrix_size::Int)
    if normal
        return sum(tr(vm) for vm in vmvec)
    else
        half = matrix_size ÷ 2
        return sum(tr(vm[1:half, 1:half]) - tr(vm[half+1:matrix_size, half+1:matrix_size]) for vm in vmvec)
    end
end

"""
    GPcore(temp, cgfm, vm)

The logarithmic determinant core of the grand-potential integrand,
`log(abs(det(I - V(k) * G'(z))))`.
"""
function GPcore(temp::AbstractMatrix, cgfm::AbstractMatrix, vm::AbstractMatrix)
    result = copy(temp)
    mul!(result, vm, cgfm, -1, 1)
    return logabsdet(result)[1]
end

"""
    GPintegrand(normal, cgfm, temp, vmvec)

Sum the grand-potential integrand over all momenta in `vmvec`.  The Gorkov
case carries the usual Nambu factor `1/2`.
"""
function GPintegrand(normal::Bool, cgfm::AbstractMatrix, temp::AbstractMatrix, vmvec::AbstractVector)
    intra = 0.0
    for vm in vmvec
        intra += GPcore(temp, cgfm, vm)
    end
    return (normal ? 1.0 : 0.5) * intra
end

function _gp_integrands(cpt::CPT, vmvec::AbstractVector, temp::AbstractMatrix, isnormal::Bool, mthreads::Integer)
    integrands = zeros(Float64, size(cpt.gfrw, 3))
    if mthreads == 1
        for i in axes(cpt.gfrw, 3)
            integrands[i] = GPintegrand(isnormal, cpt.gfrw[:, :, i], temp, vmvec)
        end
    else
        idx = Threads.Atomic{Int}(1)
        n = size(cpt.gfrw, 3)
        Threads.@sync for _ in 1:mthreads
            Threads.@spawn while true
                i = Threads.atomic_add!(idx, 1)
                i > n && break
                integrands[i] = GPintegrand(isnormal, cpt.gfrw[:, :, i], temp, vmvec)
            end
        end
    end
    return integrands
end

function _gp_tailfit_options(tailfit, nfreq::Int)
    if tailfit isa Integer
        order = Int(tailfit)
        points = min(nfreq, max(2order + 2, 8))
    elseif tailfit isa NamedTuple
        order = Int(get(tailfit, :order, 2))
        points = Int(get(tailfit, :points, min(nfreq, max(2order + 2, 8))))
    else
        throw(ArgumentError("tailfit must be `nothing`, an integer order, or a named tuple such as `(order=2, points=12)`."))
    end
    order > 0 || throw(ArgumentError("tailfit order must be positive."))
    points >= order || throw(ArgumentError("tailfit needs at least as many fit points as coefficients."))
    points <= nfreq || throw(ArgumentError("tailfit points cannot exceed the number of imaginary-frequency points."))
    return order, points
end

function _gp_tail_integral(iws::AbstractVector, integrands::AbstractVector, tailfit)
    isnothing(tailfit) && return 0.0
    length(iws) == length(integrands) || throw(DimensionMismatch("The number of imaginary-frequency points must match the number of grand-potential integrands."))
    all(iw -> iw isa Real, iws) || throw(ArgumentError("tailfit expects positive real imaginary-frequency coordinates."))
    order, points = _gp_tailfit_options(tailfit, length(iws))
    first = length(iws) - points + 1
    fit_iws = Float64.(iws[first:end])
    fit_iws[1] > 0 || throw(ArgumentError("tailfit cannot include non-positive imaginary-frequency points."))
    X = Matrix{Float64}(undef, points, order)
    for n in 1:order
        X[:, n] .= fit_iws .^ (-2n)
    end
    coeffs = X \ integrands[first:end]
    cutoff = Float64(iws[end])
    cutoff > 0 || throw(ArgumentError("tailfit cutoff must be positive."))
    tail = 0.0
    for n in 1:order
        tail += coeffs[n] / ((2n - 1) * cutoff^(2n - 1))
    end
    return tail
end
_gp_tail_integral(::Nothing, integrands::AbstractVector, ::Nothing) = 0.0

"""
    OPintegrand(cgfm, sm, vmvec, iw)

Sum the order-parameter integrand over all momenta in `vmvec` for one positive
imaginary frequency `iw`.  `sm` is the quadratic operator matrix in the same
normal or Nambu basis as `cgfm`.
"""
function OPintegrand(cgfm::AbstractMatrix, sm::AbstractMatrix, vmvec::AbstractVector, iw::Real)
    intra = 0.0
    tail = tr(sm)/(im*iw - 1.0)
    for vm in vmvec
        gfm = CPTcore(cgfm, vm)
        intra += real(tr(sm*gfm) - tail)
    end
    return intra
end

"""
    perGreenFunction(normal::Bool, GFm::AbstractMatrix, k::AbstractVector, perioder::Perioder, cluster::QLattice)

Perform the periodic procedure to cluster Green function, obtatined periodization Green function with respect to whole k-space.
"""
function perGreenFunction(normal::Bool, GFm::AbstractMatrix, k::AbstractVector, perioder::Perioder, cluster::QLattice)
    N₁, N₂, P = length(perioder.map₁), length(perioder.map₂), size(GFm, 1)÷2
    normal ? (V = 1) : (V = 4)
    normal ? (bgfv = [GFm]) : (bgfv = [GFm[1:P,1:P], GFm[1:P,(P+1):2P], GFm[(P+1):2P, 1:P], GFm[(P+1):2P, (P+1):2P]])
    gfvs = [Vector{Matrix{ComplexF64}}(undef, length(perioder.channels)) for _ in 1:V]
    pm = periodmatrix(cluster.coordinates, k)
    for i in 1:V
        for j in eachindex(perioder.channels)
            gfvs[i][j] = periodsum(perioder.map₂, bgfv[i][perioder.map₁[perioder.channels[j][1]...], perioder.map₁[perioder.channels[j][2]...]].*pm, N₂, size(cluster.coordinates,2))
        end
    end
    gfmv = [reshapematrix(N₁, N₂, gfv) for gfv in gfvs]
    normal ? (gfm = gfmv[1]) : (gfm = [gfmv[1] gfmv[2]; gfmv[3] gfmv[4]])
    return gfm
end

function periodmatrix(coordinates::AbstractMatrix, k::AbstractVector)
    L = size(coordinates,2)
    pm = Matrix{ComplexF64}(undef, L, L)
    for i in 1:L, j in 1:L
        @views ra, rb = coordinates[:, i], coordinates[:, j]
        pm[i, j] = exp(-im*dot(k, (ra - rb)))
    end
    return pm
end
function periodsum(map₂::AbstractVector, lgfm::AbstractMatrix, N::Int, L::Int)
    pgfm = Matrix{ComplexF64}(undef, N, N)
    for m in 1:N, n in 1:N
        @views cmap₂, hmap₂ = map₂[m], map₂[n]
        pgfm[m, n] = (N/L)*sum(lgfm[cmap₂, hmap₂])
    end
    return pgfm
end
function reshapematrix(N₁::Int, N₂::Int, gfv)
    gfm = Matrix{ComplexF64}(undef, N₁*N₂,  N₁*N₂)
    gfmm = reshape(gfv, (N₁, N₁))
    for i in 1:N₁, j in 1:N₁
        for u in 1:N₂, v in 1:N₂
            gfm[(i-1)*N₂ + u, (j-1)*N₂ + v] = gfmm[i, j][u, v]
        end
    end
    return gfm
end

"""
    GreenFunctionPath(normal::Bool, om::AbstractMatrix, oops::AbstractVector, oopsseqs::AbstractVector, rm::AbstractMatrix, perioder::Perioder, cluster::QLattice, k_path::Union{AbstractVector, ReciprocalSpace}, CGFm::AbstractMatrix)

Give the Green function of a certain path or area in k-space with respect to a certain energy.
"""
function GreenFunctionPath(normal::Bool, om::AbstractMatrix, oops::AbstractVector, oopsseqs::AbstractVector, rm::AbstractMatrix, perioder::Perioder, cluster::QLattice, k_path::Union{AbstractVector, ReciprocalSpace}, CGFm::AbstractMatrix; loc::Union{Nothing, AbstractVector}=nothing)
    gfpath = Vector{Matrix{ComplexF64}}(undef, length(k_path))
    if isnothing(loc)
        for i in eachindex(k_path)
            dest = copy(om)
            Vm = origiQuadraticTerms!(normal, dest, oops, oopsseqs, k_path[i]) - rm
            gfpath[i] = perGreenFunction(normal, CPTcore(CGFm, Vm), k_path[i], perioder, cluster)
        end
    else
        for i in eachindex(k_path)
            dest = copy(om)
            Vm = origiQuadraticTerms!(normal, dest, oops, oopsseqs, k_path[i]) - rm
            gfpath[i] = CPTcore(CGFm, Vm)[loc, loc]
        end
    end
    return gfpath
end 

"""
    singleParticleGreenFunction(sym::Symbol, cpt::CPT, k_path::Union{AbstractVector, ReciprocalSpace}, ω_range::Union{AbstractVector,AbstractRange}; mu::Real=0.0,  dstr::Bool=false)

The single particle Green function in k-ω space.
"""
function singleParticleGreenFunction(cpt::CPT, k_path::Union{AbstractVector, ReciprocalSpace}; mthreads::Integer=Threads.nthreads(), loc::Union{Nothing, AbstractVector}=nothing)
    oops, rops = filter(op -> length(op) == 2, collect(expand(cpt.origigenerator))), filter(op -> length(op) == 2, collect(expand(cpt.refergenerator)))
    R, N = _cpt_normal_and_size(cpt, nothing)
    oopsseqs = seqs(oops, cpt.table)
    rm = referQuadraticTerms(R, rops, zeros(ComplexF64, N, N), cpt.table)
    gfpv = Vector(undef, size(cpt.gfrw, 3))
    if mthreads == 1
        for i in 1:size(cpt.gfrw, 3)
            gfpv[i] = GreenFunctionPath(R, zeros(ComplexF64, N, N), oops, oopsseqs, rm, cpt.perioder, cpt.cluster, k_path, cpt.gfrw[:,:,i]; loc=loc)
        end
    else
        idx = Threads.Atomic{Int}(1)
        n = size(cpt.gfrw, 3)
        Threads.@sync for _ in 1:mthreads
            Threads.@spawn while true
                i = Threads.atomic_add!(idx, 1)  
                i > n && break  
                gfpv[i] = GreenFunctionPath(R, zeros(ComplexF64, N, N), oops, oopsseqs, rm, cpt.perioder, cpt.cluster, k_path, cpt.gfrw[:,:,i]; loc=loc)
            end
        end
    end
    return gfpv
end

function singleParticleGreenFunction(cpt::CPT, k_path::Union{AbstractVector, ReciprocalSpace}, fsid::Int; loc::Union{Nothing, AbstractVector}=nothing)
    oops, rops = filter(op -> length(op) == 2, collect(expand(cpt.origigenerator))), filter(op -> length(op) == 2, collect(expand(cpt.refergenerator)))
    R, N = _cpt_normal_and_size(cpt, nothing)
    oopsseqs = seqs(oops, cpt.table)
    rm = referQuadraticTerms(R, rops, zeros(ComplexF64, N, N), cpt.table)
    gfpv = Vector(undef, 1)
    gfpv[1] = GreenFunctionPath(R, zeros(ComplexF64, N, N), oops, oopsseqs, rm, cpt.perioder, cpt.cluster, k_path, cpt.gfrw[:,:,fsid]; loc=loc)
    return gfpv
end

"""
    spectrum(gfpathv::AbstractVector)

The spectrum of the single particle Green function.
"""
function spectrum(gfpathv::AbstractVector; select::AbstractVector=Vector(1:size(gfpathv[1][1],2)))
    A = zeros(Float64, length(gfpathv), length(gfpathv[1]))
        for i in eachindex(gfpathv)
            for j in eachindex(gfpathv[i])
                A[i, j] = (-1/π) * (tr(gfpathv[i][j][select, select])).im
            end
        end
        return A
end

"""
    Density of states
"""
function densityofstates(gfpathv::AbstractVector; select::AbstractVector=Vector(1:size(gfpathv[1][1],2)))
    A = zeros(Float64, length(gfpathv))
    for i in eachindex(gfpathv)
        for j in eachindex(gfpathv[i])
            A[i] += (-1/π) * (tr(gfpathv[i][j][select, select])).im
        end
    end
    return A/length(gfpathv[1])
end

function _grand_potential(cpt::CPT, bz::Union{AbstractVector, ReciprocalSpace}, E0::Real, weights::AbstractVector; normal::Union{Nothing, Bool}=nothing, mthreads::Integer=Threads.nthreads(), iws::Union{Nothing, AbstractVector}=nothing, tailfit=nothing)
    isnormal, matrix_size = _cpt_normal_and_size(cpt, normal)
    length(weights) == size(cpt.gfrw, 3) || throw(DimensionMismatch("The number of quadrature weights must match size(cpt.gfrw, 3)."))
    vmvec = _cpt_vm_matrices(isnormal, cpt, bz, matrix_size)
    temp = Matrix{ComplexF64}(I, matrix_size, matrix_size)
    integrands = _gp_integrands(cpt, vmvec, temp, isnormal, mthreads)
    if !isnothing(tailfit) && isnothing(iws)
        throw(ArgumentError("tailfit requires imaginary-frequency points; call `GrandPotential(cpt, bz, E0, iws; tailfit=...)`."))
    end
    integral = sum(weights .* integrands) + _gp_tail_integral(iws, integrands, tailfit)
    trvm = _cpt_trvm(isnormal, vmvec, matrix_size)
    return (E0 + (-integral/π + real(trvm)/2)/length(bz))/length(cpt.cluster)/length(cpt.unitcell)
end

raw"""
    GrandPotential(cpt, bz, E0, iws; normal=nothing, weights=nothing, tailfit=nothing, mthreads=nthreads())

Grand potential for a TDVP-CPT calculation whose cluster Green function has
already been transformed to the positive imaginary axis and stored in
`cpt.gfrw[:,:,n]`.

The formula is the discrete version of

```math
\\Omega = \\frac{1}{L_c L_u}\\left[
E_0 + \\frac{1}{N_k}\\left(
-\\frac{1}{\\pi}\\int_0^\\infty d\\omega\\,
\\alpha\\sum_k \\log\\left|\\det(1 - V(k)G'(i\\omega))\\right|
+ \\frac{1}{2}\\operatorname{Tr}V
\\right)\\right],
```

with `α = 1` for a normal Green function and `α = 1/2` for a Gorkov Green
function.  If `weights` is omitted, trapezoidal weights are built from `iws`.

Set `tailfit` to an integer order, for example `tailfit=2`, to fit the final
imaginary-frequency integrand points to

```math
c_2/\omega^2 + c_4/\omega^4 + \cdots
```

and add the analytic tail from `iws[end]` to infinity.  Use only imaginary
frequencies that are still reliable in the TDVP/Laplace transform; the fitted
tail cannot repair points already dominated by large-ω discretization error.
For more control, pass a named tuple such as `tailfit=(order=2, points=12)`.
"""
function GrandPotential(cpt::CPT, bz::Union{AbstractVector, ReciprocalSpace}, E0::Real, iws::AbstractVector; normal::Union{Nothing, Bool}=nothing, weights::Union{Nothing, AbstractVector}=nothing, tailfit=nothing, mthreads::Integer=Threads.nthreads())
    qweights = _gp_weights(iws, weights, size(cpt.gfrw, 3))
    return _grand_potential(cpt, bz, E0, qweights; normal=normal, mthreads=mthreads, iws=iws, tailfit=tailfit)
end

"""
    GrandPotential(cpt, bz, E0; weights, normal=nothing, mthreads=nthreads())

Grand potential with user-supplied quadrature weights for `cpt.gfrw[:,:,n]`.
Use this method for non-trapezoidal imaginary-axis grids.
"""
function GrandPotential(cpt::CPT, bz::Union{AbstractVector, ReciprocalSpace}, E0::Real; weights::Union{Nothing, AbstractVector}=nothing, normal::Union{Nothing, Bool}=nothing, mthreads::Integer=Threads.nthreads())
    isnothing(weights) && throw(ArgumentError("Pass imaginary-frequency points as `GrandPotential(cpt, bz, E0, iws)` or provide explicit `weights`."))
    qweights = _gp_weights(weights, size(cpt.gfrw, 3))
    return _grand_potential(cpt, bz, E0, qweights; normal=normal, mthreads=mthreads)
end

function _order_parameters(cpt::CPT, bz::Union{AbstractVector, ReciprocalSpace}, opterms::Tuple, iws::AbstractVector, weights::AbstractVector; normal::Union{Nothing, Bool}=nothing, mthreads::Integer=Threads.nthreads())
    isnormal, matrix_size = _cpt_normal_and_size(cpt, normal)
    length(iws) == size(cpt.gfrw, 3) || throw(DimensionMismatch("The number of imaginary-frequency points must match size(cpt.gfrw, 3)."))
    length(weights) == size(cpt.gfrw, 3) || throw(DimensionMismatch("The number of quadrature weights must match size(cpt.gfrw, 3)."))
    all(iw -> iw isa Real, iws) || throw(ArgumentError("OrderParameters expects positive real imaginary-frequency coordinates `iws`; use the same real grid passed to `fourier_riw`."))
    sm = _cpt_order_matrix(isnormal, cpt, opterms, matrix_size)
    vmvec = _cpt_vm_matrices(isnormal, cpt, bz, matrix_size)
    integrands = zeros(Float64, size(cpt.gfrw, 3))
    if mthreads == 1
        for i in axes(cpt.gfrw, 3)
            integrands[i] = OPintegrand(cpt.gfrw[:, :, i], sm, vmvec, iws[i])
        end
    else
        idx = Threads.Atomic{Int}(1)
        n = size(cpt.gfrw, 3)
        Threads.@sync for _ in 1:mthreads
            Threads.@spawn while true
                i = Threads.atomic_add!(idx, 1)
                i > n && break
                integrands[i] = OPintegrand(cpt.gfrw[:, :, i], sm, vmvec, iws[i])
            end
        end
    end
    integral = sum(weights .* integrands)
    return abs(integral/π/length(bz)/length(cpt.unitcell)/length(cpt.cluster))
end

"""
    OrderParameters(cpt, bz, opterms, iws; normal=nothing, weights=nothing, mthreads=nthreads())

Order parameter evaluated from a fixed TDVP-CPT Green function `cpt.gfrw`.
Unlike the original ED/VCA interface, this method does not update variational
or reference-Hamiltonian parameters: `opterms` only defines the quadratic
operator matrix being measured.  To scan a Weiss field or any reference
parameter, recompute the TDVP cluster Green function and construct a new `CPT`.

The discrete positive-imaginary-axis formula is

```math
\\left|\\frac{1}{N_k L_c L_u}\\frac{1}{\\pi}
\\int_0^\\infty d\\omega\\,
\\sum_k \\operatorname{Re}\\left[
\\operatorname{Tr}\\,S G_{\\mathrm{CPT}}(k,i\\omega)
- \\frac{\\operatorname{Tr}S}{i\\omega-1}
\\right]\\right|,
```

where `S` is built from `opterms` in the normal or Gorkov basis.  If `weights`
is omitted, trapezoidal weights are built from `iws`.
"""
function OrderParameters(cpt::CPT, bz::Union{AbstractVector, ReciprocalSpace}, opterms::Tuple, iws::AbstractVector; normal::Union{Nothing, Bool}=nothing, weights::Union{Nothing, AbstractVector}=nothing, mthreads::Integer=Threads.nthreads())
    qweights = _gp_weights(iws, weights, size(cpt.gfrw, 3))
    return _order_parameters(cpt, bz, opterms, iws, qweights; normal=normal, mthreads=mthreads)
end

function OrderParameters(cpt::CPT, bz::Union{AbstractVector, ReciprocalSpace}, opterm::Term, iws::AbstractVector; kwargs...)
    return OrderParameters(cpt, bz, (opterm,), iws; kwargs...)
end
